apiVersion: apps/v1
kind: Deployment
metadata:
  name: prezemi-akcija-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prezemi-akcija-backend
  template:
    metadata:
      name: prezemi-akcija-backend
      labels:
        app: prezemi-akcija-backend
    spec:
      containers:
        - name: prezemi-akcija-backend
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host
          image: fspirovski/prezemi-akcija-backend-on-k8s:v1
---
apiVersion: v1
kind: Service
metadata:
  name: prezemi-akcija-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: prezemi-akcija-backend